

metaFileName = "E:\Chimpact\test_metadata.csv";
videoPath = 'E:\Chimpact\test';
imagePath = 'E:\Chimpact\test_images_full';
imageResizeRate = 1;0.5;

% create the output dir if does not exist
[status, msg] = mkdir(imagePath);  

%% Import metadata
% Auto-generated by MATLAB on 16-Sep-2021 20:07:48

% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["video_id", "time", "x1", "y1", "x2", "y2", "probability", "Var8", "Var9"];
opts.SelectedVariableNames = ["video_id", "time", "x1", "y1", "x2", "y2", "probability"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["video_id", "Var8", "Var9"], "EmptyFieldRule", "auto");

% Import the data
testMetadata = readtable(metaFileName, opts);

% Clear temporary variables
clear opts

% %% create an empty table for the dataset
% columnNames = {'fileName', 'Animal', 'Distance'};
% datasetTable = array2table(zeros(0,3), 'VariableNames', columnNames);
% datasetTable.fileName = '';


%%

% @@@@@@@@@@@@@@@@ remove me!!
% trainLabels = trainLabels(1:1000,:);

firstRun = true;
while true  
    % pick all labels from the video that comes first in the current table
    videoName = testMetadata.video_id(1);
    currentMeta = testMetadata(strcmp(testMetadata.video_id, videoName), :);
    
    % rest of the table
    testMetadata = testMetadata(strcmp(testMetadata.video_id, videoName)==0, :); 

    myVideo = VideoReader(fullfile(videoPath, videoName));
    [~,vName,vExt] = fileparts(videoName);

    frameNo = 0;
    for i=1:height(currentMeta)

        % skip frames assuming 1 frame per second 
        while frameNo < currentMeta(i,:).time
           readFrame(myVideo);
           if ~hasFrame(myVideo)
               error('Corrupted video!');
           end
           frameNo = frameNo + 1;
        end

        % get the frame
        img = readFrame(myVideo);
        
        meta = currentMeta(currentMeta.time == frameNo, :);        
        % if no nans, we go ahead
%        if ~isnan([meta.x1 meta.y1 meta.x2 meta.y2])
            if imageResizeRate ~= 1
                imgResized = imresize(img, imageResizeRate);
            else
                imgResized = img;
            end
            imSize = size(imgResized);

            % store image
            imgFileName = [sprintf('img_%s_%s_%04d',vName,strtok(vExt,'.'),frameNo) '.png'];
            imgFileName = fullfile(imagePath, imgFileName);
            imwrite(imgResized, imgFileName);
%        end
        frameNo = frameNo + 1;
    end
    
    % if all done
    if height(testMetadata) == 0
        break;
    end

end





